### ISSUE TITLE
Why don't use rxjs version 5?

### ISSUE THREAD

**Issue by ghost** [bcherny/typed-rx-emitter#1]
I am not familiar with rxjs, but I think [version 5](https://github.com/ReactiveX/rxjs) is better managed than [version 4](https://github.com/Reactive-Extensions/RxJS).

**Comment by bcherny** [comment]
Thanks for the suggestion! What do you mean “better managed”?

**Comment by ghost** [comment]
Thank you for your quick reply. “better managed” mean It is periodically  released.

**Comment by bcherny** [comment]
That sounds like a good idea to me. Feel free to submit a PR, otherwise I will get to it at some point.

**Comment by bcherny** [comment]
Done in 240a3a78d86ad8e730abe3f4f7cbb5b31805852c.
